apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: szheerjk3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: szheerjk3-go 
  name: szheerjk3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: szheerjk3-go 
